services:
  trip:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trip
    restart: unless-stopped
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.trip.rule=Host(`trip.${LOCAL_DOMAIN_NAME}`)"
        - "traefik.http.routers.trip.entrypoints=websecure"
        - "traefik.http.routers.trip.tls=true"
        - "traefik.http.routers.trip.tls.certresolver=cloudflare"
        - "traefik.http.routers.trip.middlewares=chain-no-auth@file"
        - "traefik.http.services.trip.loadbalancer.server.port=8000"
    networks:
      - traefik_proxy
    volumes:
      - /workspace/apps_data/trip/storage:/app/storage
    environment:
      - TZ=UTC

networks:
  traefik_proxy:
    external: true
